"""Turn an extract (deps + anchors) into a human artifact: an analysis report + anchored scaffold.

This is the payoff of M3: instead of reading a strange validator repo by hand, an author gets
``<repo>-analysis.md`` (the deps verdict + the code->contract anchors + the SubnetPlugin mapping +
the open questions the tool *cannot* decide) and -- when a spec is supplied -- the M2 scaffold with
each stub's ``# >>> ANCHOR`` comment pointing at the exact source function to port. It is
draft-assist, not codegen: the four method bodies stay human/LLM work, but the map is exact.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from kata_forge.anchors import Anchor, AnchorReport, extract_anchors
from kata_forge.deps import DepReport, classify_repo
from kata_forge.generator import generate
from kata_forge.resolver import ResolvedRepo
from kata_forge.spec import SubnetSpec

# Which plugin stub each anchor kind informs (benchmark also drives benchmark_identity()).
_METHOD_FOR = {"scorer": "score", "benchmark": "sample_problems", "miner": "run_candidate"}


@dataclass(frozen=True)
class ExtractOutputs:
    """What ``write_extract`` produced: always an analysis, optionally a scaffold."""

    analysis_path: Path
    scaffold_root: Path | None = None
    scaffold_paths: list[Path] = field(default_factory=list)


def _anchor_line(anchor: Anchor | None) -> str:
    if anchor is None:
        return "_not found -- locate by hand_"
    return f"`{anchor.file}:{anchor.lineno}` **{anchor.symbol}** ({anchor.confidence}) — `{anchor.detail}`"


def render_analysis(
    *,
    subnet: int | None,
    resolved: ResolvedRepo,
    deps: DepReport,
    anchors: AnchorReport,
    spec: SubnetSpec | None = None,
) -> str:
    """Render the ``<repo>-analysis.md`` code->contract map for a resolved repo."""
    title = f"kata-forge extract — subnet {subnet}" if subnet else "kata-forge extract"
    lines = [
        f"# {title}",
        "",
        "_Auto-generated by `kata-forge extract`. Draft-assist, not codegen — verify every anchor "
        "before filling a stub._",
        "",
        "## Source",
        f"- repo: `{resolved.source}`",
        f"- commit: `{resolved.commit or '(not a git repo)'}`",
        "",
        "## Dependency verdict",
        f"- **{deps.verdict}** (parsed: {', '.join(deps.sources) or 'none'})",
    ]
    for label, names in (
        ("paid-api", deps.paid_api),
        ("gpu", deps.gpu),
        ("gated-data", deps.gated_data),
        ("unclassified (eyeball these)", deps.unclassified),
    ):
        if names:
            lines.append(f"- {label}: {', '.join(names)}")
    lines += [
        "",
        "## Code → contract anchors",
        "",
        "| plugin method | source anchor |",
        "|---|---|",
        f"| `score()` | {_anchor_line(anchors.scorer)} |",
        f"| `sample_problems()` / `benchmark_identity()` | {_anchor_line(anchors.benchmark)} |",
        f"| `run_candidate()` | {_anchor_line(anchors.miner)} |",
    ]
    if spec is not None:
        lines += [
            "",
            "## SubnetPlugin mapping",
            f"- package `{spec.package}`, class `{spec.class_name}`, evaluator `{spec.evaluator_id}`",
            f"- port the scorer into `{spec.class_name}.score`, the benchmark into "
            f"`sample_problems`, the miner contract into `run_candidate`",
        ]
    lines += [
        "",
        "## Open questions (the tool cannot decide these)",
        "- `scoring_profile`: DETERMINISTIC (fixed benchmark, reproducible) or NOISY (re-score each "
        "contender)? Default NOISY.",
        "- `environment_spec`: does the agent need network/relay or a data-provider secret, or is it "
        "fully sealed?",
        "- benchmark split: how are train/validation/holdout separated, and what is pinned?",
        "- promotion: what is the rank tuple (which metric leads, tie-breakers)?",
    ]
    return "\n".join(lines) + "\n"


def inject_anchor_todos(plugin_source: str, anchors: AnchorReport) -> str:
    """Insert a ``# >>> ANCHOR`` comment above each stub method whose source anchor was found."""
    by_method: dict[str, Anchor] = {}
    for kind, method in _METHOD_FOR.items():
        anchor = getattr(anchors, kind)
        if anchor is not None:
            by_method[method] = anchor

    out: list[str] = []
    for line in plugin_source.splitlines():
        stripped = line.lstrip()
        indent = line[: len(line) - len(stripped)]
        for method, anchor in by_method.items():
            if stripped.startswith(f"def {method}("):
                out += [
                    f"{indent}# >>> ANCHOR (kata-forge extract): port {anchor.kind} from",
                    f"{indent}#   {anchor.file}:{anchor.lineno}  {anchor.symbol}",
                    f"{indent}#   {anchor.detail}",
                ]
                break
        out.append(line)
    return "\n".join(out) + ("\n" if plugin_source.endswith("\n") else "")


def write_extract(
    *,
    out_dir: str | Path,
    subnet: int | None,
    resolved: ResolvedRepo,
    deps: DepReport | None = None,
    anchors: AnchorReport | None = None,
    spec: SubnetSpec | None = None,
    force: bool = False,
) -> ExtractOutputs:
    """Write the analysis report (always) and, given a spec, the anchor-annotated scaffold."""
    deps = deps or classify_repo(resolved.path)
    anchors = anchors or extract_anchors(resolved.path)
    out = Path(out_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    analysis_path = out / f"{resolved.path.name}-analysis.md"
    analysis_path.write_text(
        render_analysis(subnet=subnet, resolved=resolved, deps=deps, anchors=anchors, spec=spec),
        encoding="utf-8",
    )
    if spec is None:
        return ExtractOutputs(analysis_path=analysis_path)

    paths = generate(spec, out, force=force)
    scaffold_root = out / spec.repo_name
    plugin_py = next((p for p in paths if p.name == "plugin.py"), None)
    if plugin_py is not None:
        plugin_py.write_text(
            inject_anchor_todos(plugin_py.read_text(encoding="utf-8"), anchors), encoding="utf-8"
        )
    return ExtractOutputs(analysis_path=analysis_path, scaffold_root=scaffold_root, scaffold_paths=paths)
